### ISSUE TITLE
FeatureRequest: cross-platform .Substring() method for FormattedText

### ISSUE THREAD

**Issue by Emasoft** [MeilCli/CrossFormattedText#1]
This is a very useful library! Thank you for creating this!
Cross platform management of formatted strings is very hard!
This will help a lot! But I have a feature request: a cross-platform .Substring() method for FormattedText.

REASON: Many times working on .Net/Xamarin cross platforms apps I have the need to extract or replace a SUBSTRING from a FormattedString, while KEEPING the formatting on all platforms. 

But if I use methods like myFormattedString.ToString().Substring() or myFormattedString.ToString().Replace(), all the formatting is LOST.

Usually I'm forced to manually split my substrings in chunks and replace letters and substrings going span by span. But that code is long to write, ugly and error prone. 

A Substring() or Replace() method working natively on your FormattedText would be awesome.

Once you add those, it would be easy to add other standard String methods like .Insert(), .Split(), .Trim(), .Contains(), .Remove(), .IndexOf(), and so on...

I think that would make your library a must for crossplatform developers! And in the end it will replace the string class completely. Rich text is now necessary in many mobile apps (emoticons, links, bold, etc), and this library that you created is a step in the right direction.

Thank you!

**Comment by MeilCli** [comment]
Thanks nice feature request!!

First, I am not good at English.
I tried reading English as much as possible but it looks like the following:

I think add method to FormattedString class
- String like method:
  - Contains, call Contains of concatted all span text
  - EndsWith, call EndsWith of last span text
  - IndexOf, call IndexOf of concatted all span text
  - Insert, clone span data where inserted position ※Notes
  - LastIndexOf, call LastIndexOf of concatted all span text
  - Remove, span that become empty text will removed from FormattedString
  - Replace, call Replace of each span text ※Notes
  - Split, I do not know how to implement it ※Notes
  - StartsWith, call StartsWith of first span text
  - Substring, clone span data
  - ToLower and ToUpper, call its method of each span
  - Trim, call TrimStart of first span text and call TrimEnd of end span text
  - TrimStart and TrimEnd, call its method of first or last span
- String like method using span
  - Maybe the same as above
- Parse method
  - ToString(override), to html like string
  - Parse(static), from html like string

In the above method call, FormattedString must be immutable.
So I'd like to prepare the FormmatedStringBuilder class and probably do that.

※Notes
Behavior of the joint of the span is difficult.

example:

Span1 | Span2 | Span3 
------- | ------- | ------ 
some loop | occurred 1 | 200 times

- Insert text in behind of 'p' in Span1. which insert Span1 last position or Span2 first position?
- Replace to 200 from 1200 in Span2-Span3, How to insert?

Please give me a good idea.
Thank you!

**Comment by Emasoft** [comment]
@MeilCli My suggestion is to simplify things:

1) Convert internally all characters of the string to a separate Span (with all attributes)
2) Use the array of characters ( List<Span> )  to do all string operations (like a char array, only having Spans instead of chars)
3) Convert back the List<Span> to a FormattedText string

To help rebuilding the original FormattedText string Span structure, you can create a subclass of Span:

public class CharSpan: Span{
   public int span_number;
}

In that way when you rebuild the spans, you can merge all CharSpan with the same span_number in a single Span, and use the span_number to order the resulting spans when recreating the FormattedText string.

**Comment by MeilCli** [comment]
@Emasoft Thank you for your suggestion. Please give me time to try it in that direction.

**Comment by MeilCli** [comment]
work finished.

This feature is available in version 2.0.0

**Comment by Emasoft** [comment]
Awesome news!! Thank you!
